version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions: # linting libs are not ready for 5.6
    - ">=5.6.0"
  - dependency-name: "@tsconfig/node12" # breaks the config, must see why before updating
    versions:
    - ">=2.0.0"
  - dependency-name: "@types/nodes" # must be set to the Peertube required version.
  - dependency-name: "@peertube/peertube-types" # must be set to the Peertube required version.
  - dependency-name: eslint
    versions:
    - ">=9.0.0"
  - dependency-name: got
    versions:
    - ">=12.0.0" # breaking changes, must adapt code.
  - dependency-name: "@typescript-eslint/parser"
    versions: # for now 8.5.0 is broken because of the lack of ./tsconfig.json file. Must fix conf.
    - ">=8.5.0"
