image: monachus/hugo

pages:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_PATHS: support/documentation/themes/hugo-theme-learn
  script:
    # gitlab need the generated documentation to be in the /public dir.
    - hugo -s support/documentation/ -d ../../public/
  artifacts:
    paths:
      - public
  only:
    - develop
