# SPDX-FileCopyrightText: 2024 John Livingston <https://www.john-livingston.fr/>
#
# SPDX-License-Identifier: AGPL-3.0-only

baseURL = "http://localhost:1313/peertube-plugin-livechat/" # this will be overrind in CI/CD.
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Peertube plugin livechat"
theme = 'hugo-theme-relearn'

[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
  showVisitedLinks = true
  disableSearch = false
  disableLandingPageButton = true
  themeVariant = "red"

  [params.author]
    name = "John Livingston"

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repository"
url = "https://github.com/JohnXLivingston/peertube-plugin-livechat"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fab fa-git'></i> Framagit repository"
url = "https://framagit.org/Livingston/peertube-plugin-livechat"
weight = 20

[Languages]
  [Languages.en]
  title = "Peertube plugin livechat documentation"
  languageName = "English"
  contentDir = "content/en"

  [Languages.ar]
  languageName = "العربية"
  contentDir = "content/translations/ar"

  [Languages.ca]
  languageName = "Català"
  contentDir = "content/translations/ca"

  [Languages.cs]
  languageName = "Čeština"
  contentDir = "content/translations/cs"

  [Languages.de]
  title = "Peertube Plugin Livechat Dokumentation"
  languageName = "Deutsch"
  contentDir = "content/translations/de"

  [Languages.el]
  languageName = "ελληνικά"
  contentDir = "content/translations/el"

  [Languages.eo]
  languageName = "Esperanto"
  contentDir = "content/translations/eo"

  [Languages.es]
  languageName = "Español"
  contentDir = "content/translations/es"

  [Languages.eu]
  languageName = "Euskara"
  contentDir = "content/translations/eu"

  [Languages.fa]
  languageName = "فارسی"
  contentDir = "content/translations/fa"

  [Languages.fi]
  languageName = "Suomi"
  contentDir = "content/translations/fi"

  [Languages.fr]
  title = "Documentation plugin Peertube livechat"
  languageName = "Français"
  contentDir = "content/translations/fr"

  [Languages.gd]
  languageName = "Gàidhlig"
  contentDir = "content/translations/gd"

  [Languages.gl]
  languageName = "Galego"
  contentDir = "content/translations/gl"

  [Languages.hr]
  languageName = "Hrvatski"
  contentDir = "content/translations/hr"

  [Languages.hu]
  languageName = "Magyar"
  contentDir = "content/translations/hu"

  [Languages.is]
  languageName = "Íslenska"
  contentDir = "content/translations/is"

  [Languages.it]
  languageName = "Italiano"
  contentDir = "content/translations/it"

  [Languages.ja]
  title = "PeerTube ライブチャットプラグイン"
  languageName = "日本語バージョン"
  contentDir = "content/translations/ja"

  [Languages.kab]
  languageName = "Taqbaylit"
  contentDir = "content/translations/kab"

  [Languages.nb]
  languageName = "Norsk bokmål"
  contentDir = "content/translations/nb"

  [Languages.nl]
  languageName = "Nederlands"
  contentDir = "content/translations/nl"

  [Languages.nn]
  languageName = "Norsk nynorsk"
  contentDir = "content/translations/nn"

  [Languages.oc]
  languageName = "Occitan"
  contentDir = "content/translations/oc"

  [Languages.pl]
  languageName = "Polski"
  contentDir = "content/translations/pl"

  [Languages.pt]
  languageName = "uguês"
  contentDir = "content/translations/pt"

  [Languages.ru]
  languageName = "Pусский"
  contentDir = "content/translations/ru"

  [Languages.sq]
  languageName = "Shqip"
  contentDir = "content/translations/sq"

  [Languages.sv]
  languageName = "Svenska"
  contentDir = "content/translations/sv"

  [Languages.th]
  languageName = "ไทย"
  contentDir = "content/translations/th"

  [Languages.tr]
  languageName = "Türkçe"
  contentDir = "content/translations/tr"

  [Languages.tok]
  languageName = "Toki Pona"
  contentDir = "content/translations/tok"

  [Languages.uk]
  languageName = "украї́нська мо́ва"
  contentDir = "content/translations/uk"

  [Languages.vi]
  languageName = "Tiếng Việt"
  contentDir = "content/translations/vi"

  [Languages.zh-Hans]
  languageName = "简体中文（中国）"
  contentDir = "content/translations/zh-Hans"

  [Languages.zh-Hant]
  languageName = "繁體中文（台灣"
  contentDir = "content/translations/zh-Hant"
